apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  targetCPUUtilizationPercentage: 80
