apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-view
spec:
  host: view
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN		
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
